#!/bin/sh
# Jovan Lanik's fetch script 1.0
# www.github.com/jovanlanik
# clean and simple

printf "__      _  ____   ___ _____\n"
printf "\ \    // //  \\"
printf "\\  | | ||  \\"
printf "\\	\033[31mOS	\033[34m%s\033[0m\n" "$(uname -o)"
printf " \ \  // /|    |\\ | | ||   \\"
printf "\\	\033[31mDistro	\033[34m%s\033[0m\n" "$(lsb_release -c | cut -f 2)"
printf "  \ \//  \|    |/ | | ||   //	\033[31mShell	\033[34m%s\033[0m\n" "$SHELL"
printf "   \_/    \\"
printf "\\__//  |_| ||__//	%s\n\n" "Clean and Simple"

