#!/bin/sh
# Jovan Lanik's VM script 1.0
# www.github.com/jovanlanik
# clean and simple

test -z "$VM_DIR" && VM_DIR="$HOME/vms"
case $1 in
	'list')
		test "$#" -ne 1 && echo "vm: arguments wrong. See 'vm help'" && exit
		ls "$VM_DIR" | grep '.*\.qcow2' | cut -d '.' -f 1
		;;
	'make')
		test "$#" -ne 3 && echo "vm: arguments wrong. See 'vm help'" && exit
		test -z "$VM_HDA" && VM_HDA=30G
		qemu-img create -f qcow2 "$VM_DIR/$2.qcow2" $VM_HDA
		$0 exec $2 -cdrom "$3" -boot order=d
		;;
	'exec')
		test "$#" -lt 2 && echo "vm: arguments wrong. See 'vm help'" && exit
		test -z "$VM_MEM" && VM_MEM=2G
		for i in $(seq 3 $#)
		do
			eval NEW=\"\$\{$i\}\"
			ARG="$ARG $NEW"
		done
		qemu-system-x86_64 \
			-enable-kvm \
			-cpu host \
			-m $VM_MEM \
			"$VM_DIR/$2.qcow2" \
			$ARG
		;;
	'help')
		test "$#" -ne 1 && echo "vm: arguments wrong. See 'vm help'" && exit
		echo 'usage:'
		echo '	<env> vm <command> [<args>]'
		echo 'commands:'
		echo '	list'
		echo '	make <vm> <iso>'
		echo '	exec <vm>'
		echo '	help'
		echo 'environment:'
		echo '	COMMAND		VARIABLE	DEFAULT	DESCRIPTION'
		echo '	all		VM_DIR		~/vms	directory'
		echo '	make		VM_HDA		30G	disk size'
		echo '	make,exec	VM_MEM		2G	memory'
		echo 'examples:'
		echo '	$ vm make void-xfce ~/Downloads/void-live-x86_64-20191109-xfce.iso'
		echo '	$ vm exec ubuntu-20.04'
		echo '	$ VM_MEM=4G vm exec ubuntu-20.04'
		echo '	$ VM_DIR=~/virtual vm list'
		echo '	$ vm help'
		;;
	'')
		echo "vm: no command. See 'vm help'"
		;;
	*)
		echo "vm: $1 is not a vm command. See 'vm help'"
		;;
esac
